/*
 * QUANTCONNECT.COM - Democratizing Finance, Empowering Individuals.
 * Lean Algorithmic Trading Engine v2.0. Copyright 2014 QuantConnect Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

// AUTO-GENERATED by DataProcessing/generate_balancing_authorities.py - do not edit by hand.
// Constant names are derived from the EIA respondent name; values are EIA-930 codes.

namespace QuantConnect.DataSource
{
    /// <summary>
    /// Readable named constants for EIA-930 balancing authority codes, for use as the ticker in
    /// <c>AddData&lt;EIAElectricity&gt;(EIA.BalancingAuthorities.X)</c>. The major operators also
    /// carry their common short name (ERCOT, CAISO, NYISO, ISONE, SPP, BPA).
    /// </summary>
    public static partial class EIA
    {
        /// <summary>EIA-930 balancing authority codes by readable name.</summary>
        public static class BalancingAuthorities
        {
            /// <summary>PowerSouth Energy Cooperative</summary>
            public const string POWERSOUTH_ENERGY_COOPERATIVE = "AEC";
            /// <summary>Associated Electric Cooperative, Inc.</summary>
            public const string ASSOCIATED_ELECTRIC_COOPERATIVE_INC = "AECI";
            /// <summary>Avista Corporation</summary>
            public const string AVISTA_CORPORATION = "AVA";
            /// <summary>Avangrid Renewables, LLC</summary>
            public const string AVANGRID_RENEWABLES_LLC = "AVRN";
            /// <summary>Arizona Public Service Company</summary>
            public const string ARIZONA_PUBLIC_SERVICE_COMPANY = "AZPS";
            /// <summary>Balancing Authority of Northern California</summary>
            public const string BALANCING_AUTHORITY_OF_NORTHERN_CALIFORNIA = "BANC";
            /// <summary>Bonneville Power Administration</summary>
            public const string BPA = "BPAT";
            /// <summary>Bonneville Power Administration</summary>
            public const string BONNEVILLE_POWER_ADMINISTRATION = "BPAT";
            /// <summary>California</summary>
            public const string CALIFORNIA = "CAL";
            /// <summary>Carolinas</summary>
            public const string CAROLINAS = "CAR";
            /// <summary>Central</summary>
            public const string CENTRAL = "CENT";
            /// <summary>Public Utility District No. 1 of Chelan County</summary>
            public const string PUBLIC_UTILITY_DISTRICT_NO_1_OF_CHELAN_COUNTY = "CHPD";
            /// <summary>California Independent System Operator</summary>
            public const string CAISO = "CISO";
            /// <summary>California Independent System Operator</summary>
            public const string CALIFORNIA_INDEPENDENT_SYSTEM_OPERATOR = "CISO";
            /// <summary>Duke Energy Progress East</summary>
            public const string DUKE_ENERGY_PROGRESS_EAST = "CPLE";
            /// <summary>Duke Energy Progress West</summary>
            public const string DUKE_ENERGY_PROGRESS_WEST = "CPLW";
            /// <summary>Arlington Valley, LLC</summary>
            public const string ARLINGTON_VALLEY_LLC = "DEAA";
            /// <summary>PUD No. 1 of Douglas County</summary>
            public const string PUD_NO_1_OF_DOUGLAS_COUNTY = "DOPD";
            /// <summary>Duke Energy Carolinas</summary>
            public const string DUKE_ENERGY_CAROLINAS = "DUK";
            /// <summary>Electric Energy, Inc.</summary>
            public const string ELECTRIC_ENERGY_INC = "EEI";
            /// <summary>El Paso Electric Company</summary>
            public const string EL_PASO_ELECTRIC_COMPANY = "EPE";
            /// <summary>Electric Reliability Council of Texas, Inc.</summary>
            public const string ERCOT = "ERCO";
            /// <summary>Electric Reliability Council of Texas, Inc.</summary>
            public const string ELECTRIC_RELIABILITY_COUNCIL_OF_TEXAS_INC = "ERCO";
            /// <summary>Florida</summary>
            public const string FLORIDA = "FLA";
            /// <summary>Florida Municipal Power Pool</summary>
            public const string FLORIDA_MUNICIPAL_POWER_POOL = "FMPP";
            /// <summary>Duke Energy Florida, Inc.</summary>
            public const string DUKE_ENERGY_FLORIDA_INC = "FPC";
            /// <summary>Florida Power &amp; Light Co.</summary>
            public const string FLORIDA_POWER_LIGHT_CO = "FPL";
            /// <summary>Public Utility District No. 2 of Grant County, Washington</summary>
            public const string PUBLIC_UTILITY_DISTRICT_NO_2_OF_GRANT_COUNTY_WASHINGTON = "GCPD";
            /// <summary>GridLiance</summary>
            public const string GRIDLIANCE = "GLHB";
            /// <summary>Gridforce Energy Management, LLC</summary>
            public const string GRIDFORCE_ENERGY_MANAGEMENT_LLC = "GRID";
            /// <summary>Griffith Energy, LLC</summary>
            public const string GRIFFITH_ENERGY_LLC = "GRIF";
            /// <summary>Gainesville Regional Utilities</summary>
            public const string GAINESVILLE_REGIONAL_UTILITIES = "GVL";
            /// <summary>NaturEner Power Watch, LLC</summary>
            public const string NATURENER_POWER_WATCH_LLC = "GWA";
            /// <summary>New Harquahala Generating Company, LLC</summary>
            public const string NEW_HARQUAHALA_GENERATING_COMPANY_LLC = "HGMA";
            /// <summary>City of Homestead</summary>
            public const string CITY_OF_HOMESTEAD = "HST";
            /// <summary>Imperial Irrigation District</summary>
            public const string IMPERIAL_IRRIGATION_DISTRICT = "IID";
            /// <summary>Idaho Power Company</summary>
            public const string IDAHO_POWER_COMPANY = "IPCO";
            /// <summary>ISO New England</summary>
            public const string ISONE = "ISNE";
            /// <summary>ISO New England</summary>
            public const string ISO_NEW_ENGLAND = "ISNE";
            /// <summary>JEA</summary>
            public const string JEA = "JEA";
            /// <summary>Los Angeles Department of Water and Power</summary>
            public const string LOS_ANGELES_DEPARTMENT_OF_WATER_AND_POWER = "LDWP";
            /// <summary>LG&amp;E and KU Services Company as agent for Louisville Gas and Electric Company and Kentucky Utilities Company</summary>
            public const string LG_E_AND_KU_SERVICES_COMPANY_AS_AGENT_FOR_LOUISVILLE_GAS_AND_ELECTRIC_COMPANY_AND_KENTUCKY_UTILITIES_COMPANY = "LGEE";
            /// <summary>Mid-Atlantic</summary>
            public const string MID_ATLANTIC = "MIDA";
            /// <summary>Midwest</summary>
            public const string MIDWEST = "MIDW";
            /// <summary>Midcontinent Independent System Operator, Inc.</summary>
            public const string MISO = "MISO";
            /// <summary>Midcontinent Independent System Operator, Inc.</summary>
            public const string MIDCONTINENT_INDEPENDENT_SYSTEM_OPERATOR_INC = "MISO";
            /// <summary>New England</summary>
            public const string NEW_ENGLAND = "NE";
            /// <summary>Nevada Power Company</summary>
            public const string NEVADA_POWER_COMPANY = "NEVP";
            /// <summary>Utilities Commission of New Smyrna Beach</summary>
            public const string UTILITIES_COMMISSION_OF_NEW_SMYRNA_BEACH = "NSB";
            /// <summary>Northwest</summary>
            public const string NORTHWEST = "NW";
            /// <summary>NorthWestern Corporation</summary>
            public const string NORTHWESTERN_CORPORATION = "NWMT";
            /// <summary>New York</summary>
            public const string NEW_YORK = "NY";
            /// <summary>New York Independent System Operator</summary>
            public const string NYISO = "NYIS";
            /// <summary>New York Independent System Operator</summary>
            public const string NEW_YORK_INDEPENDENT_SYSTEM_OPERATOR = "NYIS";
            /// <summary>PacifiCorp East</summary>
            public const string PACIFICORP_EAST = "PACE";
            /// <summary>PacifiCorp West</summary>
            public const string PACIFICORP_WEST = "PACW";
            /// <summary>Portland General Electric Company</summary>
            public const string PORTLAND_GENERAL_ELECTRIC_COMPANY = "PGE";
            /// <summary>PJM Interconnection, LLC</summary>
            public const string PJM = "PJM";
            /// <summary>PJM Interconnection, LLC</summary>
            public const string PJM_INTERCONNECTION_LLC = "PJM";
            /// <summary>Public Service Company of New Mexico</summary>
            public const string PUBLIC_SERVICE_COMPANY_OF_NEW_MEXICO = "PNM";
            /// <summary>Public Service Company of Colorado</summary>
            public const string PUBLIC_SERVICE_COMPANY_OF_COLORADO = "PSCO";
            /// <summary>Puget Sound Energy, Inc.</summary>
            public const string PUGET_SOUND_ENERGY_INC = "PSEI";
            /// <summary>South Carolina Public Service Authority</summary>
            public const string SOUTH_CAROLINA_PUBLIC_SERVICE_AUTHORITY = "SC";
            /// <summary>Dominion Energy South Carolina, Inc.</summary>
            public const string DOMINION_ENERGY_SOUTH_CAROLINA_INC = "SCEG";
            /// <summary>Seattle City Light</summary>
            public const string SEATTLE_CITY_LIGHT = "SCL";
            /// <summary>Southeast</summary>
            public const string SOUTHEAST = "SE";
            /// <summary>Seminole Electric Cooperative</summary>
            public const string SEMINOLE_ELECTRIC_COOPERATIVE = "SEC";
            /// <summary>Southeastern Power Administration</summary>
            public const string SOUTHEASTERN_POWER_ADMINISTRATION = "SEPA";
            /// <summary>Sikeston Board of Municipal Utilities</summary>
            public const string SIKESTON_BOARD_OF_MUNICIPAL_UTILITIES = "SIKE";
            /// <summary>Southern Company Services, Inc. - Trans</summary>
            public const string SOUTHERN_COMPANY_SERVICES_INC_TRANS = "SOCO";
            /// <summary>Southwestern Power Administration</summary>
            public const string SOUTHWESTERN_POWER_ADMINISTRATION = "SPA";
            /// <summary>Salt River Project Agricultural Improvement and Power District</summary>
            public const string SALT_RIVER_PROJECT_AGRICULTURAL_IMPROVEMENT_AND_POWER_DISTRICT = "SRP";
            /// <summary>Southwest</summary>
            public const string SOUTHWEST = "SW";
            /// <summary>Southwest Power Pool</summary>
            public const string SPP = "SWPP";
            /// <summary>Southwest Power Pool</summary>
            public const string SOUTHWEST_POWER_POOL = "SWPP";
            /// <summary>City of Tallahassee</summary>
            public const string CITY_OF_TALLAHASSEE = "TAL";
            /// <summary>Tampa Electric Company</summary>
            public const string TAMPA_ELECTRIC_COMPANY = "TEC";
            /// <summary>Tennessee</summary>
            public const string TENNESSEE = "TEN";
            /// <summary>Tucson Electric Power</summary>
            public const string TUCSON_ELECTRIC_POWER = "TEPC";
            /// <summary>Texas</summary>
            public const string TEXAS = "TEX";
            /// <summary>Turlock Irrigation District</summary>
            public const string TURLOCK_IRRIGATION_DISTRICT = "TIDC";
            /// <summary>City of Tacoma, Department of Public Utilities, Light Division</summary>
            public const string CITY_OF_TACOMA_DEPARTMENT_OF_PUBLIC_UTILITIES_LIGHT_DIVISION = "TPWR";
            /// <summary>Tennessee Valley Authority</summary>
            public const string TENNESSEE_VALLEY_AUTHORITY = "TVA";
            /// <summary>United States Lower 48</summary>
            public const string UNITED_STATES_LOWER_48 = "US48";
            /// <summary>Western Area Power Administration - Rocky Mountain Region</summary>
            public const string WESTERN_AREA_POWER_ADMINISTRATION_ROCKY_MOUNTAIN_REGION = "WACM";
            /// <summary>Western Area Power Administration - Desert Southwest Region</summary>
            public const string WESTERN_AREA_POWER_ADMINISTRATION_DESERT_SOUTHWEST_REGION = "WALC";
            /// <summary>Western Area Power Administration - Upper Great Plains West</summary>
            public const string WESTERN_AREA_POWER_ADMINISTRATION_UPPER_GREAT_PLAINS_WEST = "WAUW";
            /// <summary>NaturEner Wind Watch, LLC</summary>
            public const string NATURENER_WIND_WATCH_LLC = "WWA";
            /// <summary>Alcoa Power Generating, Inc. - Yadkin Division</summary>
            public const string ALCOA_POWER_GENERATING_INC_YADKIN_DIVISION = "YAD";
        }
    }
}
